### ISSUE TITLE
希望在UIWebView的浏览器UA字段中加入开发者头条的特有标识

### ISSUE THREAD

**Issue by zhuyingda** [judi0713/TouTiao#7]
RT，原因是我个人的博客为了防野爬，对UA和一些浏览器特征嗅探结果做了严格的筛选，近期发现大量
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko)`
这样的UA的http请求被机器人拦截器拦截，我猜测都是这个mac插件的使用用户。
所以希望能加个UA标识符，这样方便个人博主对你的头条mac插件的网络请求进行加白和放行

**Comment by tesths** [comment]
我用的博客链接是从开发者头条的链接跳转到博客链接的，我只爬了开发者头条的网站。

**Comment by zhuyingda** [comment]
你没明白我的意思，你的客户端里是不是有个webview 里面可以打开头条上的其他博客？

**Comment by judi0713** [comment]
这个..我懂了，我不是开发者头条官方app的开发者..我是学生，仅仅开发了mac端的插件而已。我帮你反馈到他们技术那边吧~

**Comment by tesths** [comment]
你的意思是手机客户端的问题？

**Comment by zhuyingda** [comment]
额，不是指手机客户端，是指osx上面。不好意思 我并没用过你这个mac插件，你的插件提供的功能只是把一个网页分享到toutiao.io吗？ 你的插件是否可以当一个浏览器来用？ 比如用你这个插件 来浏览开发者头条上面的一些博客而不是用浏览器

**Comment by zhuyingda** [comment]
你说的  “只爬了开发者头条的网站”  这句话的意思是  你的插件中有一个爬虫？  我想知道 你的爬虫是否带有这样的一个UA（useragent）？

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko)`

**Comment by tesths** [comment]
我的插件用了swift的网络请求库直接请求的开发者头条网站，然后解析的xml，把网站的数据显示出来，里面没有使用webview，不能在插件里查看，打开博客的话是直接在用户用的浏览器里面打开

**Comment by zhuyingda** [comment]
感谢你的详细回答， 想问一下 你使用swift的 网络请求库 “直接请求开发者头条网站，然后解析xml”这个行为是通过http协议吗？还是基于其他特殊的RPC？ 如果是http协议 你的请求是否相当于个爬虫，会去递归地抓取开发者头条网站上面的各个博客url的内容？

**Comment by tesths** [comment]
是http协议。我没有直接的爬个人的博客和个人博客在开发者头条上的链接，网络请求也只有一条请求，请求了toutiao.io，没有请求其他的。我刚刚也已经抓包测试了。插件里所有博主的博客链接都是经过开发者头条的链接，一个toutiao为域名的url二次跳转到个人博主博客界面的。我已经向开发者头条那边的技术反馈你的问题了，他们会看下是不是其他地方出了问题。

**Comment by zhuyingda** [comment]
事实上开发者头条网站上面的博客url 都是类似这样的：

`http://toutiao.io/j/myc18i`

当浏览器 或者任何http client访问这类url时，开发者头条网站会以302的方式 将http请求重定向到博客原本的url
比如你访问我发的这个url时候，会被重定向到一篇我的个人博客：

`https://www.zhuyingda.com/blog/article.html?id=6&hmsr=toutiao.io&utm_medium=toutiao.io&utm_source=toutiao.io?hmsr=toutiao.io&utm_medium=toutiao.io&utm_source=toutiao.io`

你可以在浏览器里抓包试一下，我在想 你的网络请求库收到这个302之后 有没有可能又去请求一次重定向之后的页面呢？

**Comment by tesths** [comment]
我的网络请求库不会请求除了 `http://toutiao.io` 这个之外的其他任何一条链接。我抓包试过了。

**Comment by tesths** [comment]
点击插件里的列表话就直接在浏览器打开 `http://toutiao.io/j/myc18i` 这种链接了。插件自身不会发送任何其他的网络请求。
